; PlatformIO Project Configuration File

[platformio]
src_dir = main

[env:lilygo-t-display-s3]
platform = espressif32
board = lilygo-t-display-s3
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
upload_flags = 
    --after
    no_reset

build_flags = 
    -D USB_CDC_ENABLED=1
    -fcommon
    -Wno-error
    -Wno-error=deprecated-declarations
    -Wno-error=maybe-uninitialized
    -Wl,--allow-multiple-definition