#pragma once

#include <stdint.h>

// QR code for the About screen, generated by tools/gen_qr.py. Bit 7 of the first byte is the left-most module; 1 is dark.
#define ABOUT_QR_SIZE 33

extern const char about_qr_url[];
extern const uint8_t about_qr_rows[ABOUT_QR_SIZE][(ABOUT_QR_SIZE + 7) / 8];
