#pragma once

#include <stdint.h>

// Anti-aliased ASCII 32..126, one 0-255 coverage value per pixel, generated by tools/gen_font.py
#define FONT_SMALL_W 8
#define FONT_SMALL_H 13
#define FONT_LARGE_W 16
#define FONT_LARGE_H 16

extern const uint8_t font_small[95][FONT_SMALL_W * FONT_SMALL_H];
extern const uint8_t font_large[95][FONT_LARGE_W * FONT_LARGE_H];
