#!/usr/bin/env python3
"""Generate main/font_aa.c: anti-aliased ASCII fonts for the dongle's screen, rendered from DejaVu Sans Mono.

    python3 tools/gen_font.py [--preview preview.png]

DejaVu fonts are free to use and embed (Bitstream Vera licence, see https://dejavu-fonts.github.io/License.html).
Two fonts are produced: a small one (8 x 13 cells) and a large one (16 x 16 cells, bold, used at double size).
Each glyph is a table of 0-255 coverage values; the display code blends the text color over the background.
"""
import argparse
import os
import sys
from PIL import Image, ImageDraw, ImageFont

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REGULAR = "/usr/share/fonts/TTF/DejaVuSansMono.ttf"
BOLD = "/usr/share/fonts/TTF/DejaVuSansMono-Bold.ttf"
SUPER = 4

# name, font path, cell width, cell height, baseline row, font size, gamma (below 1 makes thin strokes stronger)
FONTS = [
    ("small", REGULAR, 8, 13, 10, 13.0, 0.7),
    ("large", BOLD, 16, 16, 13, 19.0, 1.0),
]


def render(path, cw, ch, base, size, gamma, ch_code):
    font = ImageFont.truetype(path, size * SUPER)
    adv = font.getlength("M") / SUPER
    img = Image.new("L", (int(adv * SUPER) + 8 * SUPER, ch * SUPER), 0)
    draw = ImageDraw.Draw(img)
    draw.text((4 * SUPER, base * SUPER), chr(ch_code), font=font, fill=255, anchor="ls")
    # keep the glyph box: advance wide, starting at the left bearing offset
    box = img.crop((4 * SUPER, 0, 4 * SUPER + int(round(adv * SUPER)), ch * SUPER))
    box = box.resize((cw, ch), Image.BOX if box.width >= cw else Image.LANCZOS)
    return [round(255 * (v / 255) ** gamma) for v in box.get_flattened_data()]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--preview")
    args = ap.parse_args()

    out = ["// Generated by tools/gen_font.py from DejaVu Sans Mono (free licence). Do not edit by hand.",
           '#include "font_aa.h"', ""]
    previews = []
    for name, path, cw, ch, base, size, gamma in FONTS:
        out.append(f"const uint8_t font_{name}[95][{cw * ch}] = {{")
        glyphs = []
        for code in range(32, 127):
            data = render(path, cw, ch, base, size, gamma, code)
            glyphs.append(data)
            out.append("    {" + ",".join(str(v) for v in data) + "},  // " + (chr(code) if chr(code) != "\\" else "backslash"))
        out.append("};")
        out.append("")
        previews.append((name, cw, ch, glyphs))
    open(os.path.join(ROOT, "main", "font_aa.c"), "w").write("\n".join(out))

    if args.preview:
        text = "READY 0123456789 Hello World, gypq 0x7E8 P0101-07 CAN OK"
        h = sum(ch + 6 for _, _, ch, _ in previews) + 8
        img = Image.new("RGB", (len(text) * 16 + 16, h), (0, 0, 0))
        y = 4
        for name, cw, ch, glyphs in previews:
            for i, c in enumerate(text):
                g = glyphs[ord(c) - 32]
                for j, v in enumerate(g):
                    x, yy = i * cw + 8 + j % cw, y + j // cw
                    img.putpixel((x, yy), (v, v, v))
            y += ch + 6
        img = img.resize((img.width * 3, img.height * 3), Image.NEAREST)
        img.save(args.preview)


if __name__ == "__main__":
    sys.exit(main())
