#!/usr/bin/env python3
"""Generate main/about_qr.c: the QR code on the About screen, as a table of dark/light modules.

    pip install segno
    python3 tools/gen_qr.py [--url https://github.com/<owner>/<repo>]

The code is made at build time so the dongle needs no QR encoder. It is version 4 (33 x 33 modules) with medium error correction,
so a URL of up to 62 bytes fits. Edit this script's default URL, or pass --url, then rebuild.
"""
import argparse
import os
import sys

import segno

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_URL = "https://github.com/NotActuallyBlue/esp32s3-isotp-gvret"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--url", default=DEFAULT_URL)
    args = ap.parse_args()

    qr = segno.make(args.url, error="m", version=4, mode="byte", boost_error=False, micro=False)
    rows = [[1 if cell else 0 for cell in row] for row in qr.matrix]
    size = len(rows)

    out = [f"// Generated by tools/gen_qr.py for {args.url}. Do not edit by hand.",
           '#include "about_qr.h"', "",
           f'const char about_qr_url[] = "{args.url}";',
           f"const uint8_t about_qr_rows[ABOUT_QR_SIZE][(ABOUT_QR_SIZE + 7) / 8] = {{"]
    for row in rows:
        packed = []
        for i in range(0, size, 8):
            byte = 0
            for b in range(8):
                byte <<= 1
                if i + b < size and row[i + b]:
                    byte |= 1
            packed.append(f"0x{byte:02X}")
        out.append("    {" + ", ".join(packed) + "},")
    out.append("};")
    open(os.path.join(ROOT, "main", "about_qr.c"), "w").write("\n".join(out) + "\n")

    header = f'''#pragma once

#include <stdint.h>

// QR code for the About screen, generated by tools/gen_qr.py. Bit 7 of the first byte is the left-most module; 1 is dark.
#define ABOUT_QR_SIZE {size}

extern const char about_qr_url[];
extern const uint8_t about_qr_rows[ABOUT_QR_SIZE][(ABOUT_QR_SIZE + 7) / 8];
'''
    open(os.path.join(ROOT, "main", "about_qr.h"), "w").write(header)
    print(f"{size} x {size} modules for {args.url}")


if __name__ == "__main__":
    sys.exit(main())
