#!/usr/bin/env python3
"""Generate main/font.c from a Linux console PSF font (8 pixels wide).

    python3 tools/gen_font.py [--psf /usr/share/kbd/consolefonts/lat2-14.psfu.gz]

The screen uses one 8 x 14 bitmap font. Headers, status lines and counters use the same glyphs doubled in width (16 x 14).
Edit this script, not the generated file. Check the font's licence before shipping a product that includes it.
"""
import argparse
import gzip
import os
import struct
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_PSF = "/usr/share/kbd/consolefonts/lat2-14.psfu.gz"


def load_psf(path):
    data = gzip.open(path).read() if path.endswith(".gz") else open(path, "rb").read()
    if data[:2] == b"\x36\x04":                         # PSF1
        height, bytes_per_glyph, offset = data[3], data[3], 4
    else:                                               # PSF2
        _, _, offset, _, _, bytes_per_glyph, height, width = struct.unpack("<8I", data[:32])
        if width != 8:
            sys.exit("only 8 pixel wide fonts are supported")

    def glyph(code):
        raw = data[offset + code * bytes_per_glyph: offset + (code + 1) * bytes_per_glyph]
        return [[(raw[row] >> (7 - x)) & 1 for x in range(8)] for row in range(height)]
    return height, glyph


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--psf", default=DEFAULT_PSF)
    args = ap.parse_args()
    height, glyph = load_psf(args.psf)

    out = ["// Generated by tools/gen_font.py from " + os.path.basename(args.psf) + ". Do not edit by hand.",
           '#include "font.h"', "",
           f"const uint8_t font_small[95][FONT_SMALL_W * FONT_SMALL_H] = {{"]
    large = []
    for code in range(32, 127):
        rows = glyph(code)
        label = chr(code) if chr(code) != "\\" else "backslash"
        out.append("    {" + ",".join("255" if v else "0" for row in rows for v in row) + "},  // " + label)
        large.append("    {" + ",".join("255" if v else "0" for row in rows for v in row for _ in (0, 1)) + "},  // " + label)
    out += ["};", "", "const uint8_t font_large[95][FONT_LARGE_W * FONT_LARGE_H] = {"] + large + ["};", ""]
    open(os.path.join(ROOT, "main", "font.c"), "w").write("\n".join(out))

    header = f'''#pragma once

#include <stdint.h>

// ASCII 32..126, one 0-255 coverage value per pixel, generated by tools/gen_font.py
#define FONT_SMALL_W {8}
#define FONT_SMALL_H {height}
#define FONT_LARGE_W {16}
#define FONT_LARGE_H {height}

extern const uint8_t font_small[95][FONT_SMALL_W * FONT_SMALL_H];
extern const uint8_t font_large[95][FONT_LARGE_W * FONT_LARGE_H];
'''
    open(os.path.join(ROOT, "main", "font.h"), "w").write(header)


if __name__ == "__main__":
    sys.exit(main())
